# Generated by Django 5.0.4 on 2024-06-18 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentLocal',
            fields=[
                ('content_local_id', models.AutoField(help_text='ID Khoá chính', primary_key=True, serialize=False)),
                ('content_local_name', models.TextField(blank=True, help_text='Tên danh mục, kiểu input', max_length=200, null=True)),
                ('content_local_description', models.TextField(blank=True, help_text='Mô tả chi tiết, kiểu textarea', max_length=1000, null=True)),
                ('content_local_enable', models.BooleanField(blank=True, null=True)),
                ('content_local_status', models.BooleanField(blank=True, default=True, null=True)),
                ('content_local_created_at', models.DateTimeField(auto_now_add=True)),
                ('content_local_updated_at', models.DateTimeField(auto_now=True)),
                ('content_local_user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ContentLocal_content_local_user_created', to=settings.AUTH_USER_MODEL)),
                ('content_local_user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ContentLocal_content_local_user_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'content_local',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('content_id', models.AutoField(help_text='ID Khoá chính', primary_key=True, serialize=False)),
                ('content_name', models.TextField(blank=True, help_text='Tên danh mục, kiểu input', max_length=200, null=True)),
                ('content_description', models.TextField(blank=True, help_text='Mô tả chi tiết, kiểu textarea', max_length=1000, null=True)),
                ('content_enable', models.BooleanField(blank=True, null=True)),
                ('content_status', models.BooleanField(blank=True, default=True, null=True)),
                ('content_created_at', models.DateTimeField(auto_now_add=True)),
                ('content_updated_at', models.DateTimeField(auto_now=True)),
                ('content_user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Content_content_user_created', to=settings.AUTH_USER_MODEL)),
                ('content_user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Content_content_user_updated', to=settings.AUTH_USER_MODEL)),
                ('content_local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Content_content_local', to='content.contentlocal')),
            ],
            options={
                'db_table': 'content',
            },
        ),
    ]
