# Generated by Django 5.0.4 on 2024-06-21 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='content_image',
            field=models.ImageField(blank=True, null=True, upload_to='tinni/static'),
        ),
    ]
