# Generated by Django 5.0.4 on 2024-06-21 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_content_content_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='content_image',
        ),
    ]
