# Generated by Django 5.0.4 on 2024-06-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_content_content_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_price',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
    ]
